### ISSUE TITLE
Add support for multiple systems

### ISSUE THREAD

**Issue by sndpl** [maziac/z80dismblr#9]
Hi, thanks for this nice program! I wanted to add support for the MSX system but at the moment the code base contains some ZX Spectrum specific code (file reading, opcodes) which is not abstracted. So that's why I created this ticket to discuss the needed changes if you want to support multiple systems :)  

At the moment I added a --msx-bin param which detect if it's a binary file or ROM file (both have a different file header). With the detected start address I set the snaStartAddress and the disassembly works :) 

The second thing I would like to add is MSX specific comments for bios- and port- and system addresses. So when the code does a call to a bios subroutine, ex: 
 
; MSX Bios routine, call 0x00A2
0x00A2 CHPUT ; display the char on screen

it would be nice if it writes: `call CHPUT  	; 00A2h` in the disassembled source code and adds the sub with this name instead of SUB<x> (already hacked this in the code, but it's not generic enough).

Same if the code does an in/out to a port, it would be nice if it shows the port description in the comment:
```
in      a,(0x99)        ; VDP address/reg. write
out     (0xA0),a        ; AY-3-8910 PSG address Reg
```
and for system addresses add the description of this system address:
```
ld      (0xf3e9),a      ; set foreground color
ld      a,(0xf3e9)      ; get foreground color
```

I think some of this is already implemented for the Spectrum Next in the opcode file? I tried this with the comments feature (with the ini file), but that only works for data labels at the moment. 

Also the latest MSX (TurboR) has a R800 processor which is a Z80 with 2 new instructions (MULUB does unsigned 8bit multiplication, and the MULUW instructions does 16bit unsigned multiplication). I can add the instructions in the OpcodesED (they are still free), but somehow it would be nicer if it is some kind of abstracted in separate classes. That a system can extend the base opcode and add opcodes or functions for label/comments (and add a new cli param to select the system).

So if you want to support multiple systems (there are a lot of 8bit systems that use the z80), I'm willing to help with the MSX implementation :)  else you can close this ticket.

**Comment by maziac** [comment]
Since I used these tools mainly for Spectrum and ZX Next development there are a few "extensions" that slipped in for these machines.

I could certainly find a way to make this little more generic and then have a command line option to choose the instruction set.

For the "0x00A2 CHPUT":
I think this should be configurable already with the '--lblsin' option.
Please have a look [here](https://github.com/maziac/z80dismblr#interactive-usage).

For the in/out, system addresses:
I think the above also works for ports. I.e. if you add a name for a label it might also show up for a port.
But I'm not sure, maybe it does not work for in/out. (And maybe it could clash with memory address labels).
The comment (ASFAIR) is not changed in these cases, but maybe that's OK if the label has a good name.

The in/out has another problem. If you have something like this:
~~~asm
ld bc,0x1234
out (c),a
~~~
only for the 'ld bc,...' the named label can be used, the 'out' itself would be left unchanged.









At the moment I'm not extending the z80dsmblr, but you can easily fork the project. 
Or, if you have just small additions you can create a PR and I can merge it.
(I'm hesitating on bigger changes because I use it also inside another project, DeZog, which could mean bigger changes there as well.)
